-- USER
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(50),
  USERNAME VARCHAR(64),
  PASSWORD VARCHAR(32),
  WEIGHT DOUBLE,
  CREATE_TIME TIMESTAMP,
  BIRTH DATE,
  SEX INT,
  OLDER BOOLEAN
);

-- ROLE
DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(50),
  DESC VARCHAR(100)
);

-- USER_ROLE
DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE(
  USER_ID INT,
  ROLE_ID INT,
  PRIMARY KEY(USER_ID, ROLE_ID)
);

-- HOBBY
DROP TABLE IF EXISTS HOBBY;
CREATE TABLE HOBBY(
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(20),
  USER_ID INT,
);
